### ISSUE TITLE
Accordion Component working in author, publish environment but fails in dispatcher

### ISSUE THREAD

**Issue by ghost** [AdobeDocs/experience-manager-core-components.en#16]
Hi,
we have enabled the core components and proxy the Accordion component on to the site. The Accordion works  as expected in author and publish environment but fails in dispatcher. The accordion component rte field doesn't  expand.  There is no trace of errors  either in dispatcher or console.log. 
Link to the dispatcher :  http://qaweb.nonprodaem.cnb.com/content/cnbcom/en/campaigns/test/awareness-demo.html

Publisher working image:
![accordion_publish](https://user-images.githubusercontent.com/30687553/82976147-2ea81e00-9f93-11ea-84e9-4b92d99a7150.PNG)

**Comment by bohnertchris** [comment]
Hello, @yaswanthv007. Thank you for raising an issue. However this is the repository for the documentation of the core components. If you have an issue with using the components, I would ask you to raise an issue in the core components repository [1] or via our normal customer care channels [2].

[1] https://github.com/adobe/aem-core-wcm-components
[2] https://helpx.adobe.com/contact/enterprise-support.ec.html
