### ISSUE TITLE
Anchor Link to Build List Using Search Broken

### ISSUE THREAD

**Issue by jdpitt13** [AdobeDocs/experience-manager-core-components.en#2]
Issue in help/using/list.md

The anchor link in the sidebar under On This Page > Edit Dialog > List Settings Tab > Search is broken. The href is pointing to "#search" which is an id on the wrapper div for that section, but it looks like CSS and possibly something more global is using the same id, which I'm guessing, is conflicting (who uses an id in a stylesheet anyway!? ;-) ). Possible solution would be to use a different id in the div wrapper and href. 

As as side note, sidebar won't appear unless your viewport is > 1400px.

**Comment by bohnertchris** [comment]
Thank you for spotting this, @jdpitt13. This was corrected during the migration but somehow seems to have crept back in. Corrected in commit 2ccaf8a.

**Comment by bohnertchris** [comment]
Closing as complete with commit 2ccaf8a.
