### ISSUE TITLE
Update the instructions to be more detailed

### ISSUE THREAD

**Issue by lha-adobe** [AdobeDocs/experience-manager-core-components.en#21]
Issue in ./help/developing/data-layer/overview.md

Regarding https://docs.adobe.com/content/help/en/experience-manager-core-components/using/developing/data-layer/overview.html#installation-activation

See below #1 has more details

NEW Detailed:
1. Create the following structure below the /conf node:
- /conf/<mySite>/sling:configs/com.adobe.cq.wcm.core.components.internal.DataLayerConfig
- com.adobe.cq.wcm.core.components.internal.DataLayerConfig node type: nt:unstructured , sling:configs node type: sling:Folder
2. Add a boolean property called enabled and set it to true .
3. Add a sling:configRef property to the jcr:content node of your site below /content (e.g. /content/<mySite>/jcr:content ) and set it to /conf/<mySite> .

OLD :
1. Create the following structure below the /conf node:
- /conf/<mySite>/sling:configs/com.adobe.cq.wcm.core.components.internal.DataLayerConfig
- Node type: nt:unstructured
2. Add a boolean property called enabled and set it to true .
3. Add a sling:configRef property to the jcr:content node of your site below /content (e.g. /content/<mySite>/jcr:content ) and set it to /conf/<mySite> .

Also, please rephrase this sentence :
> Once enabled, you can verify the activation by loading a page of the site outside of the editor. When you inspect the page you will see that the Adobe Client Data Layer is loaded.

Once enabled, validate the activation by loading a page in "View as Published" mode. When you inspect the page you will see that the Adobe Client Data Layer is loaded.

**Comment by anujkapo** [comment]
Thanks, @lha-adobe. We will take a look.

**Comment by bohnertchris** [comment]
Thanks for reporting this, @lha-adobe , and apologies for how long it took to respond. It appears that something has gone wrong with our alert filters on this repo. We will look into it.

Regarding the issue, this has since been clarified in the docs.
