### ISSUE TITLE
Anchor links does not work

### ISSUE THREAD

**Issue by vdhaliwa** [AdobeDocs/experience-manager-core-components.en#22]
Issue in ./help/components/button.md

Clicking on the Anchor links "configure dialog" and "design dialog" in the Usage section does not do anything. 

Expected: Links should take the user to appropriate headings.

**Comment by anujkapo** [comment]
Thanks, @vdhaliwa. We will fix the links.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16805.

**Comment by bohnertchris** [comment]
This was a known issue related to our recent migration of documentation content to the Experience League platform. It has since been fixed by the platform team.
