### ISSUE TITLE
Replace the word "Image" with "button" in Styles Tab section

### ISSUE THREAD

**Issue by vdhaliwa** [AdobeDocs/experience-manager-core-components.en#23]
Issue in ./help/components/button.md

Issue: Replace the word "Image" with "button" in the very last line of doc.

Expected The Button Component supports the AEM Style System .

**Comment by anujkapo** [comment]
Thanks, @vdhaliwa. We will fix it.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16806.

**Comment by bohnertchris** [comment]
This was fixed with commit 0fbf641.
