### ISSUE TITLE
Incorrect Module Descriptions

### ISSUE THREAD

**Issue by bstopp** [AdobeDocs/experience-manager-core-components.en#24]
Issue in ./help/developing/archetype/using.md

Archetype 24 removed `it.launcher` and introduced `ui.tests` modules.

The documentation has been incorrectly updated to describe the `ui.tests` as Java tests - these are actually WebDriver.IO JavaScript tests.

The `it.launcher` module was renamed to `ui.launcher` instead of being removed from the list.

A new entry `ui.tests` is needed to provide context for that module, and the current entry should be renamed back to `it.tests`.

**Comment by bohnertchris** [comment]
Thanks for reporting this, @bstopp. The suggested changes will be rolled out with the next release of the Core Components.
