### ISSUE TITLE
Unreadable image for the Post Form Data

### ISSUE THREAD

**Issue by gabrielwalt** [AdobeDocs/experience-manager-core-components.en#28]
Issue in ./help/components/forms/form-container.md
The image illustrating the Post Form Data dialog is barely readable, something is wrong in its resolution or JPEG quality. The other images on the same page look all good.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for reporting this, @gabrielwalt. It is unclear how the image was corrupted, but I have uploaded a new, clear one.
