### ISSUE TITLE
How do i use it?

### ISSUE THREAD

**Issue by mesahach** [AdobeDocs/experience-manager-core-components.en#30]
I don`t understand. Please what am i to download?

**Comment by aheim0** [comment]
See:
- https://experienceleague.adobe.com/docs/experience-manager-core-components/using/get-started/using.html?lang=en#download-and-install 

What to download depends on which version of AEM you are using:
- AEM as a Cloud Service: Nothing to download, they are included
- AEM 6.5 and AEM 6.4: You need to download the package from Git. See the download link under:
-- https://experienceleague.adobe.com/docs/experience-manager-core-components/using/get-started/using.html?lang=en#aem-65 

We hope that helps.
