### ISSUE TITLE
Archetype should handle hyphens or document should call out the constraint

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/experience-manager-core-components.en#31]
Issue in ./help/developing/archetype/overview.md

This issue is applicable to both the links below

- https://github.com/adobe/aem-project-archetype
- https://experienceleague.adobe.com/docs/experience-manager-core-components/using/developing/archetype/overview.html?lang=en

If you specify the groupId with a '-' in it, the projects gets created but the code fails in the build. It would be good if we handle this. Some options

1. Project creation fails fast with the error that the group id is invalid.
2. The hyphens in groupId field are replaced with . or _ or some other valid characters. 
3. documentation calls out the WARNING explicitly.

**Comment by bohnertchris** [comment]
Hello @himanshu-pathak and thank you for the suggestion for our documentation. We will review to update the docs. If you wish for a change to the code, please consider creating a PR with your suggestion against the Core Components repository.

https://github.com/adobe/aem-core-wcm-components

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
We expanded our documentation of the groupId parameter with commit edfe50e in our docs and commit 67ad97d of the archetype repository. Thank you for reporting this.
