### ISSUE TITLE
Wow! Awesome Documentation!

### ISSUE THREAD

**Issue by XLpacman805** [AdobeDocs/experience-manager-core-components.en#33]
Issue in ./help/developing/success.md

Not an issue. I just wanna say I’m 3 days into learning AEM working with a React SPA and these docs are some of the best docs I’ve ever read. 

Just the fact that the docs even talk about success and failpoints highlights the quality of these docs. Breadth alone is not inherently a good thing, but these docs have breadth of everything that is relevant to software developers. 

This exceeded my expectations, and the effort that went into making the documentation / tutorials is much appreciated. Thanks.

y’all should make a blog post for engineers about your strategy for this.

**Comment by aheim0** [comment]
Many thanks for your feedback, that is very kind and encouraging. I'll make sure that your comments are passed on to the writers involved.

I'll close this ticket now, but do not hesitate to get in touch again if you have issues. 

Thanks.
