### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/experience-manager-core-components.en#34]
Issue in ./help/components/content-fragment-component.md

The "Component Library" link on this page is broken:

https://aemcomponents.dev/content/core-components-examples/library/page-authoring/content-fragment.html - 404

**Comment by bohnertchris** [comment]
Thank you for reporting this, @bbringhu. We will fix it.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
The underlying GoURL (shortened link) was updated and will be pushed out at 07:50 UTC tomorrow.
