### ISSUE TITLE
Social Sharing - Needs to mention deprecation

### ISSUE THREAD

**Issue by james-collier** [AdobeDocs/experience-manager-core-components.en#36]
Issue in ./help/components/sharing.md

This [Social Sharing component](https://github.com/adobe/aem-core-wcm-components/tree/core.wcm.components.reactor-2.20.4/content/src/content/jcr_root/apps/core/wcm/components/sharing/v1/sharing) has been DEPRECATED since Core Components 2.18.0, but this doc page makes no mention of this.

**Comment by aheim0** [comment]
Thanks for raising this - we will review.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for reporting this, @james-collier. This was corrected in commit c2ee8c9.
