### ISSUE TITLE
Documentation links for form components broken

### ISSUE THREAD

**Issue by woodstepha** [AdobeDocs/experience-manager-core-components.en#37]
Issue in ./help/components/forms/form-container.md

Leads to 404 error. Applies to all form components in documentation: 
https://experienceleague.adobe.com/docs/experience-manager-core-components/using/components/forms/form-container.html?lang=en

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for reporting this, @woodstepha. However I am unable to reproduce any issue with the forms components. It could be that you encountered this after we did some redirect updates and they had not been fully populated across our load balancers. If you still encounter problems, please create another issue.
