### ISSUE TITLE
Documentation indicates that the current version is v1, but should be v2

### ISSUE THREAD

**Issue by yumeniiru** [AdobeDocs/experience-manager-core-components.en#38]
> The current version of the Quick Search Component is v1, which was introduced with release 2.0.0 of the Core Components in January 2018, and is described in this document.

**Comment by aheim0** [comment]
Thanks for highlighting this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for reporting this, @yumeniiru. This was corrected in commit c2ee8c9.
