### ISSUE TITLE
List V3 screenhot in V2 documentation

### ISSUE THREAD

**Issue by arunpatidar02** [AdobeDocs/experience-manager-core-components.en#39]
Issue in .[/help/components/v2/list.md](https://github.com/AdobeDocs/experience-manager-core-components.en/blob/main/help/components/v2/list.md#item-settings-tab-item-settings-tab)

https://experienceleague.adobe.com/docs/experience-manager-core-components/using/components/v2-components/list.html?lang=en#item-settings-tab 

The List V2 at Item Settings Tab {#item-settings-tab} contains V3 dialog screenshot

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
CQDOC-19605

**Comment by bohnertchris** [comment]
Thank you for reporting this, @arunpatidar02. This was corrected in commit c2ee8c9.
