### ISSUE TITLE
Accordion Link to the GITHUB is broken

### ISSUE THREAD

**Issue by veevik** [AdobeDocs/experience-manager-core-components.en#40]
Issue in ./help/components/accordion.md

The link to accordion in the below text in the page is broken 
**_The latest technical documentation about the Accordion Component [can be found on GitHub](https://adobe.com/go/aem_cmp_tech_accordion_v1)._**

**Comment by bohnertchris** [comment]
Thank you for reporting this, @veevik. We will have a look.

CQDOC-19607

**Comment by bohnertchris** [comment]
Hello, @veevik. It looks like some of our redirects expired. I have reviewed the active components and updated the links where necessary. However, these will not be live until tomorrow (30.08.) at 08:50 CEST. If you still see errors, please create a new issue after that time. Sorry for the inconvenience.

Note that all component technical details can be found in the Core Components GitHub repo. https://github.com/adobe/aem-core-wcm-components
Examples of component usage can be found here: https://aemcomponents.dev
