### ISSUE TITLE
ui.apps pom does not have embedded tags for the filevault-package-maven-plugin

### ISSUE THREAD

**Issue by synox** [AdobeDocs/experience-manager-core-components.en#43]
> ui.apps/pom.xml
> The ui.apps pom (<src>/<project>/ui.apps/pom.xml) provides the embedded tags for the filevault-package-maven-plugin. The embedded tags include the compiled core bundle as part of the ui.apps package and where it will be installed.

I don't see `<embedded>` in `ui.apps/pom.xml`, but I do see them in `all/pom.xml`.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was corrected in commit 537c8d0.
