### ISSUE TITLE
Deprecated NPM module

### ISSUE THREAD

**Issue by krassib** [AdobeDocs/experience-manager-core-components.en#45]
Issue in ./help/developing/archetype/uifrontend-react.md

The link
https://www.npmjs.com/package/@adobe/cq-react-editable-components
should be
https://www.npmjs.com/package/@adobe/aem-react-editable-components

**Comment by TylerRush** [comment]
Thanks for your feedback @krassib. I have updated the link. The updates will appear on this page later today.

**Comment by TylerRush** [comment]
The link appears on this page: https://experienceleague.adobe.com/docs/experience-manager-core-components/using/developing/archetype/uifrontend-react.html?lang=en
