### ISSUE TITLE
Table of Contents | Not able to understand how this component works from the given documentation

### ISSUE THREAD

**Issue by vikrave** [AdobeDocs/experience-manager-core-components.en#46]
Issue in ./help/components/tableofcontents.md

We are trying to follow this documentation, but nothing is getting displayed on the page. We think the documentation is not clear enough to explain how the content will get rendered. Either the component is not working or the documentation is not clear enough for us to follow and get this working.

Could you please review this ?

**Comment by anujkapo** [comment]
Thanks, @vikrave. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by vikrave** [comment]
@anujkapo I think the documentation is missing an important configuration details as mentioned in this comment https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/core-components-table-of-contents-how-does-it-work/m-p/570913/highlight/true#M142610

**Comment by bohnertchris** [comment]
This was addressed with commit 0af7552.
