### ISSUE TITLE
Missing links inside the "Sample Component Output" section for the Email Components + Compatible with Cloud Service question

### ISSUE THREAD

**Issue by yakulto** [AdobeDocs/experience-manager-core-components.en#48]
I was looking at the Email Components documentation and saw that all of the "Sample Component Output" sections in the components (9 of them, the Page Component does not have the said section) are leading to 404s:

Affected Documentation Pages:
1. https://experienceleague.adobe.com/docs/experience-manager-core-components/using/email/components/container.html?lang=en
2. https://experienceleague.adobe.com/docs/experience-manager-core-components/using/email/components/title.html?lang=en
3. https://experienceleague.adobe.com/docs/experience-manager-core-components/using/email/components/text.html?lang=en
4. https://experienceleague.adobe.com/docs/experience-manager-core-components/using/email/components/image.html?lang=en
5. https://experienceleague.adobe.com/docs/experience-manager-core-components/using/email/components/button.html?lang=en
6. https://experienceleague.adobe.com/docs/experience-manager-core-components/using/email/components/teaser.html?lang=en
7. https://experienceleague.adobe.com/docs/experience-manager-core-components/using/email/components/experience-fragment.html?lang=en
8. https://experienceleague.adobe.com/docs/experience-manager-core-components/using/email/components/content-fragment.html?lang=en
9. https://experienceleague.adobe.com/docs/experience-manager-core-components/using/email/components/segmentation.html?lang=en

The links that lead to 404s inside those pages are

1. https://adobe.com/go/aem_cmp_library_email_container
2. https://adobe.com/go/aem_cmp_library_email_title
3. https://adobe.com/go/aem_cmp_library_email_text
4. https://adobe.com/go/aem_cmp_library_email_image
5. https://adobe.com/go/aem_cmp_library_email_button
6. https://adobe.com/go/aem_cmp_library_email_teaser
7. https://adobe.com/go/aem_cmp_library_email_xf
8. https://adobe.com/go/aem_cmp_library_email_cf
9. https://adobe.com/go/aem_cmp_library_email_segmentation

Also all the component pages seem to mention that the Email components are Compatible with AEM Cloud Service but in the 
Introduction page it's mentioned that it's not: https://experienceleague.adobe.com/docs/experience-manager-core-components/using/email/introduction.html?lang=en

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by anujkapo** [comment]
Thanks, @yakulto. We will look into it.

**Comment by bohnertchris** [comment]
This has been corrected with commit be6fc6e.
