### ISSUE TITLE
"Multi-Module Maven Project" Diagram needs to be updated

### ISSUE THREAD

**Issue by Rahul-Kumar-AIG** [AdobeDocs/experience-manager-core-components.en#50]
Issue in ./help/developing/archetype/using.md
[https://experienceleague.adobe.com/docs/experience-manager-core-components/using/developing/archetype/using.html?lang=en](https://experienceleague.adobe.com/docs/experience-manager-core-components/using/developing/archetype/using.html?lang=en)

In ablove url "Multi-Module Maven Project" diagram depicts that core-bundle is a part of "ui.apps" but according to latest maven archetype "core bundle" is embedded as part of "all" module .

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was corrected in commit 28f70cf.
