### ISSUE TITLE
Update versions page to reflect 2.23.2 deployment in CS

### ISSUE THREAD

**Issue by holmsj** [AdobeDocs/experience-manager-core-components.en#51]
Issue in ./help/versions.md 

This page shows 2.22.12 as the latest Core release. 

According to comments in SITES-14545 Jira story, **2.23.2** is deployed to CS. My testing in Sandboxes seems to confirm the same. 

Please update the page to correctly identify the latest release in Cloud Service.

**Comment by anujkapo** [comment]
Thanks, @holmsj. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This page documents the versions of the Core Components available to any user of AEM, Cloud Service, on prem, or AMS. As such it reflects the release information in the Core Components GitHub repo.

https://github.com/adobe/aem-core-wcm-components/releases

Information about what version is included in Cloud Service is documented in the AEM as a Cloud Service release notes.
