### ISSUE TITLE
Broken link to Adaptive Image Servlet

### ISSUE THREAD

**Issue by lklement** [AdobeDocs/experience-manager-core-components.en#52]
Issue in ./help/components/image.md

The link in the first tip to a discussion or page on the Adaptive Image Servlet appears to be broken.  It look like it currently goes to a non-existant anchor in the same page.

Please see the document [Adaptive Image Servlet](https://experienceleague.adobe.com/docs/experience-manager-core-components/using/wcm-components/image.html?lang=en#adaptive-image-servlet) for details on how it works.

**Comment by rickbrough** [comment]
Link is now fixed in Core Components Help (https://experienceleague.adobe.com/docs/experience-manager-core-components/using/wcm-components/image.html?lang=en#responsive-features), dated 10/10/23 or later. Thank you for logging the issue.

**Comment by rickbrough** [comment]
Link is now fixed in Core Components Help (https://experienceleague.adobe.com/docs/experience-manager-core-components/using/wcm-components/image.html?lang=en#responsive-features), dated 10/10/23 or later. Thank you for logging the issue.
