### ISSUE TITLE
Core Components are not Compatible with Static Templates

### ISSUE THREAD

**Issue by kalva2290** [AdobeDocs/experience-manager-core-components.en#8]
Issue in help/using/using.md
Issue in help/using/authoring.md

The contributors to the Core Components project state that core components will not work with static templates, but the documentation specifically states that it would work for both. Please update the docs to reflect the current state of affairs. 

See below issues describing that Static Templates are not supported:
https://github.com/adobe/aem-core-wcm-components/issues/100
https://github.com/adobe/aem-core-wcm-components/issues/551

**Comment by bohnertchris** [comment]
Thanks for pointing this out, @kalva2290. I have updated the docs to clearly state that only editable templates are supported. I also added links to our new [AEM Modernize Tools Suite](https://github.com/adobe/aem-modernize-tools), which I encourage you to check out if you haven't already. It contains migration tools to move from static to editable templates amongst others.

**Comment by bohnertchris** [comment]
Fixed with commit a1d725b6fc32112323e9939e8870922410a6c4f3
