### ISSUE TITLE
Component Library Link Broken in Breadcrumb

### ISSUE THREAD

**Issue by jdpitt13** [AdobeDocs/experience-manager-core-components.en#9]
Issue in help/using/breadcrumb.md

The link to Component Library is broken under Sample Component Output section.

**Current href:** http://opensource.adobe.com/aem-core-wcm-components/library/breadcrumb.html

**Possible correct href:** http://opensource.adobe.com/aem-core-wcm-components/library/breadcrumb/hidden/level-1/level-2/breadcrumb.html

**Comment by bohnertchris** [comment]
Thanks for pointing this out, @jdpitt13 ! This was fixed with eef608f.
